mutation LogInAsVulcast($vulcastId : String!, $secret : String!) {
  logInAsVulcast(vulcastId: $vulcastId, secret: $secret) {
    __typename
    ... on VulcastAuthentication {
      vulcastAccessToken
    }
    ... on AuthenticationError {
      message
    }
  }
}

mutation AssignVulcastToRelay {
  assignVulcastToRelay {
    __typename
    ... on RelayAssignment {
      relay {
        hostName
      }
      relayAccessToken
    }
    ... on AuthenticationError {
      message
    }
    ... on VulcastAssignedToRelayError {
      message
    }
  }
}
